config/routes.rb
Rails.application.routes.draw do

  resources :logs

  # root 'errors#pardon'
  # get '/*any_route', to: 'errors#pardon', as: 'pardon'

  resources :visits
  resources :dependencies
  resources :models
  resources :packages
  resources :releases
  resources :downloads
  resources :subscriptions
  resources :feeds
  resources :settings
  resources :blurbs
  resources :references
  resources :trending_weekly_news_items
  resources :trending_daily_news_items
  resources :trending_monthly_news_items
  resources :stack_overflow_news_items
  resources :discourse_news_items
  resources :github_news_items
  resources :reddit_news_items
  resources :activities
  resources :batches
  resources :infos
  resources :profiles
  resources :labels
  resources :organizations
  resources :contributions
  resources :users
  resources :bots
  resources :dummies
  resources :categories
  resources :daters
  resources :counters
  resources :versions
  resources :repositories

  resources :news, as: :news_items, controller: :news_items

  resources :searches do
    get 'autocomplete', on: :collection
  end

  resource :trending

  resources :searches, path: 's'

  resource :trending, path: 't'

  resources :users, path: 'u'
  resources :packages, path: 'p'
  resources :organizations, path: 'o'

  get 'about', to: 'statics#about'

  root 'trendings#index'

  get '/*bad_route', to: 'errors#index', as: 'errors'

end

app/models/repository.rb
# == Schema Information
#
# Table name: repositories
#
#  id         :integer          not null, primary key
#  package_id :integer
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_repositories_on_package_id  (package_id)
#

class Repository < ApplicationRecord
  belongs_to :package
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repository_params
      params.require(:repository).permit(:package_id, :url)
    end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(repository) do |f| %>
  <% if repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :package_id %>
    <%= f.text_field :package_id %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repositories</h1>

<table>
  <thead>
    <tr>
      <th>Package</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= repository.package %></td>
        <td><%= repository.url %></td>
        <td><%= link_to 'Show', repository %></td>
        <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
        <td><%= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Package:</strong>
  <%= @repository.package %>
</p>

<p>
  <strong>Url:</strong>
  <%= @repository.url %>
</p>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>