config/routes.rb
Rails.application.routes.draw do

  resources :logs

  # root 'errors#pardon'
  # get '/*any_route', to: 'errors#pardon', as: 'pardon'

  resources :visits
  resources :dependencies
  resources :models
  resources :packages
  resources :releases
  resources :downloads
  resources :subscriptions
  resources :feeds
  resources :settings
  resources :blurbs
  resources :references
  resources :trending_weekly_news_items
  resources :trending_daily_news_items
  resources :trending_monthly_news_items
  resources :stack_overflow_news_items
  resources :discourse_news_items
  resources :github_news_items
  resources :reddit_news_items
  resources :activities
  resources :batches
  resources :infos
  resources :profiles
  resources :labels
  resources :organizations
  resources :contributions
  resources :users
  resources :bots
  resources :dummies
  resources :categories
  resources :daters
  resources :counters
  resources :versions
  resources :repositories

  resources :news, as: :news_items, controller: :news_items

  resources :searches do
    get 'autocomplete', on: :collection
  end

  resource :trending

  resources :searches, path: 's'

  resource :trending, path: 't'

  resources :users, path: 'u'
  resources :packages, path: 'p'
  resources :organizations, path: 'o'

  get 'about', to: 'statics#about'

  root 'trendings#index'

  get '/*bad_route', to: 'errors#index', as: 'errors'

end

app/models/contribution.rb
# == Schema Information
#
# Table name: contributions
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  package_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  score      :integer
#
# Indexes
#
#  index_contributions_on_package_id  (package_id)
#  index_contributions_on_uniqueness  (user_id,package_id) UNIQUE
#  index_contributions_on_user_id     (user_id)
#

class Contribution < ApplicationRecord
  belongs_to :user
  belongs_to :package
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  # GET /contributions
  # GET /contributions.json
  def index
    @contributions = Contribution.all
  end

  # GET /contributions/1
  # GET /contributions/1.json
  def show
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = Contribution.new(contribution_params)

    respond_to do |format|
      if @contribution.save
        format.html { redirect_to @contribution, notice: 'Contribution was successfully created.' }
        format.json { render :show, status: :created, location: @contribution }
      else
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to @contribution, notice: 'Contribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: 'Contribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.require(:contribution).permit(:user_id, :package_id)
    end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<%= form_for(contribution) do |f| %>
  <% if contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :package_id %>
    <%= f.text_field :package_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contributions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Package</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contributions.each do |contribution| %>
      <tr>
        <td><%= contribution.user %></td>
        <td><%= contribution.package %></td>
        <td><%= link_to 'Show', contribution %></td>
        <td><%= link_to 'Edit', edit_contribution_path(contribution) %></td>
        <td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contribution', new_contribution_path %>

app/views/contributions/new.html.erb
<h1>New Contribution</h1>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @contribution.user %>
</p>

<p>
  <strong>Package:</strong>
  <%= @contribution.package %>
</p>

<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>