config/routes.rb
Rails.application.routes.draw do

  resources :logs

  # root 'errors#pardon'
  # get '/*any_route', to: 'errors#pardon', as: 'pardon'

  resources :visits
  resources :dependencies
  resources :models
  resources :packages
  resources :releases
  resources :downloads
  resources :subscriptions
  resources :feeds
  resources :settings
  resources :blurbs
  resources :references
  resources :trending_weekly_news_items
  resources :trending_daily_news_items
  resources :trending_monthly_news_items
  resources :stack_overflow_news_items
  resources :discourse_news_items
  resources :github_news_items
  resources :reddit_news_items
  resources :activities
  resources :batches
  resources :infos
  resources :profiles
  resources :labels
  resources :organizations
  resources :contributions
  resources :users
  resources :bots
  resources :dummies
  resources :categories
  resources :daters
  resources :counters
  resources :versions
  resources :repositories

  resources :news, as: :news_items, controller: :news_items

  resources :searches do
    get 'autocomplete', on: :collection
  end

  resource :trending

  resources :searches, path: 's'

  resource :trending, path: 't'

  resources :users, path: 'u'
  resources :packages, path: 'p'
  resources :organizations, path: 'o'

  get 'about', to: 'statics#about'

  root 'trendings#index'

  get '/*bad_route', to: 'errors#index', as: 'errors'

end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id           :integer          not null, primary key
#  feed_id      :integer
#  news_item_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_subscriptions_on_feed_id       (feed_id)
#  index_subscriptions_on_news_item_id  (news_item_id)
#

class Subscription < ApplicationRecord
  belongs_to :feed
  belongs_to :news_item
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:feed_id, :news_item_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(subscription) do |f| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feed_id %>
    <%= f.text_field :feed_id %>
  </div>

  <div class="field">
    <%= f.label :news_item_id %>
    <%= f.text_field :news_item_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Feed</th>
      <th>News item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.feed %></td>
        <td><%= subscription.news_item %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feed:</strong>
  <%= @subscription.feed %>
</p>

<p>
  <strong>News item:</strong>
  <%= @subscription.news_item %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>