config/routes.rb
Rails.application.routes.draw do

  resources :logs

  # root 'errors#pardon'
  # get '/*any_route', to: 'errors#pardon', as: 'pardon'

  resources :visits
  resources :dependencies
  resources :models
  resources :packages
  resources :releases
  resources :downloads
  resources :subscriptions
  resources :feeds
  resources :settings
  resources :blurbs
  resources :references
  resources :trending_weekly_news_items
  resources :trending_daily_news_items
  resources :trending_monthly_news_items
  resources :stack_overflow_news_items
  resources :discourse_news_items
  resources :github_news_items
  resources :reddit_news_items
  resources :activities
  resources :batches
  resources :infos
  resources :profiles
  resources :labels
  resources :organizations
  resources :contributions
  resources :users
  resources :bots
  resources :dummies
  resources :categories
  resources :daters
  resources :counters
  resources :versions
  resources :repositories

  resources :news, as: :news_items, controller: :news_items

  resources :searches do
    get 'autocomplete', on: :collection
  end

  resource :trending

  resources :searches, path: 's'

  resource :trending, path: 't'

  resources :users, path: 'u'
  resources :packages, path: 'p'
  resources :organizations, path: 'o'

  get 'about', to: 'statics#about'

  root 'trendings#index'

  get '/*bad_route', to: 'errors#index', as: 'errors'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord

  include Batchable

  extend FriendlyId
  friendly_id :name

  has_many :labels, dependent: :destroy
  has_many :packages, through: :labels

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category
      .active_batch_scope
      .joins(:packages)
      .group("categories.id")
      .order("count(categories.id) desc")
      .limit(100)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    raw_params = params.with_indifferent_access
    raw_params[:category_id] = raw_params.delete :id

    @sort, @packages = \
      PackageSorterJob.perform_now raw_params, cookies
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.custom_find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% page_title 'Categories' %>

<div class="cs-main-area cs-full-width">

  <div class="panel panel-default">

    <div class="panel-heading">

      <h3 class="cs-no-margin cs-full-width cs-center">
        Categories
      </h3>

    </div>

    <div class="panel-body">

      <table class="table table-striped table-hover cs-no-margin">

        <thead>

          <tr>

            <th>#</th>
            <th>Category</th>
            <th class='hidden-xs'>Top Packages</th>
            <th class='hidden-xs hidden-sm'></th>
            <th class='hidden-xs hidden-sm hidden-md'></th>
            <th>Pkg<span class="hidden visible-xs" style="display: inline-block !important;">s</span><span class="hidden-xs"> Count</span></th>

          </tr>

        </thead>

        <tbody>

          <% @categories.each_with_index do |category, index| %>

            <tr>

              <td><%= index + 1 %></td>
              <td><%= link_to category.name, category_path(category) %></td>

              <%
                  limit_count = 3

                  package_query = category.packages.includes(:counter)
                  package_query = package_query.order("counters.stargazer desc")
                  package_query = package_query.first(limit_count)

                  padding_vars = [ {} ] * ( limit_count - package_query.count )

                  category_packages = package_query + padding_vars
              %>

              <% category_packages.each_with_index do |package, sub_index| %>

                <%
                    data_class = 'hidden-xs'
                    data_class += ' hidden-sm' if sub_index > 0
                    data_class += ' hidden-md' if sub_index > 1
                %>

                <td class='<%= data_class %>'>

                  <% package_name = package.try(:name) %>

                  <% if package_name.present? %>
                    <%= link_to truncate(package_name, length: 20), package_path(package) %>
                  <% else %>
                    -
                  <% end %>

                </td>

              <% end %>

              <td><%= category.packages.count %></td>

            </tr>

          <% end %>

        </tbody>

      </table>

    </div>

    <%= render 'layouts/fork_footer' %>

  </div>

</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%
  page_title @category.name
  page_description "Julia packages underneath the #{@category.name} category"
%>

<%= render 'layouts/package_main_area' %>

<%= render 'layouts/default_side_bar' %>

<%= render 'layouts/pagination_js' %>

<script>
  var categoriesDiv = $("#js-sidebar-categories__<%= @category.name.gsub(' ', '-').underscore.dasherize %>");
  if ( categoriesDiv ) {
    $('.cs-side-bar .panel-body').animate({
      scrollTop: categoriesDiv.offset().top - 0.5 * $(document).height() - 25
    }, 0);
  }
</script>

app/views/categories/show.js.erb
var appendedSelector = '.cs-main-area .cs-main-panel .list-group',
    appendedList = `<%=
      escape_javascript render partial: \
        'layouts/package_list', \
        locals: { packages: @packages }
    %>`;

$(appendedSelector).append(appendedList);

var paginationSelector = '.pagination',
    newPagination = `<%=
      escape_javascript render partial: \
        'layouts/package_pagination', \
        locals: { packages: @packages }
    %>`;

$(paginationSelector).replaceWith(newPagination);

$("a[href='#top']").click(function() {
  $("html, body, .cs-main-area").animate({ scrollTop: 0 }, "slow");
  return false;
});